# Compatibility check: https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge
# Proof read: make sure spelled correctly, right syntax, open and close "". Yaml won't check it for you! 

- topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"

- ros_topic_name: "model/auv/raw_sim_imu"
  gz_topic_name: "model/auv/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "model/auv/raw_sim_pose"
  gz_topic_name: "model/auv/pose"
  ros_type_name: "geometry_msgs/msg/Pose"	
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS
