# Compatibility check: https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge
# Proof read: make sure spelled correctly, right syntax, open and close "". Yaml won't check it for you! 

# ign topic -t /model/rov/joint/thruster1_joint/cmd_thrust -m ignition.msgs.Double -p 'data: 100000000'
# ros2 topic pub /thruster1  std_msgs/msg/Float64 "{data: 0}"

- gz_topic_name: "model/rov/X150_sim"
  ros_topic_name: "X150_sim"
  ros_type_name: "geometry_msgs/msg/Vector3"
  gz_type_name: "gz.msgs.Vector3d"
  direction: GZ_TO_ROS

- gz_topic_name: "model/rov/joint/thruster1_joint/cmd_thrust"
  ros_topic_name: "thruster1"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster2_joint/cmd_thrust"
  ros_topic_name: "thruster2"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster3_joint/cmd_thrust"
  ros_topic_name: "thruster3"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster4_joint/cmd_thrust"
  ros_topic_name: "thruster4"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster5_joint/cmd_thrust"
  ros_topic_name: "thruster5"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster6_joint/cmd_thrust"
  ros_topic_name: "thruster6"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster7_joint/cmd_thrust"
  ros_topic_name: "thruster7"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

- gz_topic_name: "model/rov/joint/thruster8_joint/cmd_thrust"
  ros_topic_name: "thruster8"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ